CREATE DATABASE IF NOT EXISTS tmd_db;
USE tmd_db;

CREATE TABLE IF NOT EXISTS sketches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_data TEXT NOT NULL,
    created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 